### ISSUE TITLE
Can't get mypy to start from `LSP-pylsp`

### ISSUE THREAD

**Issue by StabbarN** [Richardk2n/mypy-ls#9]
I want to enable mypy (preferably dmypy) with Sublime and LSP-pylsp but I can't get mypy to run.
Linting and formatting in Sublime works fine.

My sublime-project file:
```
{
	...
	"settings":
	{
        "python_interpreter": "/Users/me/code/proj/.venv/bin/python",
	}
}
```

My LSP-pylsp.sublime-settings:
```
{
	"settings": {
        "pylsp.plugins.mypy_ls.enabled": true,
		...
    }
}
```

I've tried setting live_mode to true or false: `"pylsp.plugins.mypy-ls.live_mode": true,`

I've tried creating a mypy-ls.cfg file in my project's root with the following content but to no avail:
cat mypy-ls.cfg
```
{
    "enabled": True,
    "live_mode": False,
    "dmypy": True,
    "strict": False
}
```

Executing dmypy (and mypy) from terminal works fine.
When I have opened sublime dmypy isn't started `dmypy status` says "No status file found". So it seems that dmypy isn't started.

In Sublime I've set `log_server": ["panel"]` and checked what's sent to pylsp but it seems fine.

```
ls .venv
_pyenv_version bin            include        lib            pyvenv.cfg     share
which mypy
/Users/me/code/proj/.venv/bin/mypy
which dmypy
/Users/me/code/proj/venv/bin/dmypy
```

Please advice what more I can do to debug this.

**Comment by Richardk2n** [comment]
There seems to be some ambiguity weather mypy_ls or mypy-ls works for the config (meaning try `"pylsp.plugins.mypy-ls.enabled": true,`)

Can you confirm other plugins run?

Can you confirm weather mypy-ls is started and misbehaving or if it is not even started?

**Comment by StabbarN** [comment]
> There seems to be some ambiguity weather mypy_ls or mypy-ls works for the config (meaning try "pylsp.plugins.mypy-ls.enabled": true,)

Changing to `"pylsp.plugins.mypy-ls.enabled": true,` didn't help me.

> Can you confirm other plugins run?

Other plugins run excellent, such as:
```
        "pylsp.configurationSources": [
            "flake8"
        ],
        "pylsp.plugins.flake8.enabled": true,
        "pylsp.plugins.pyls_isort.enabled": true,
        "pylsp.plugins.pylsp_black.enabled": true,

```


> Can you confirm weather mypy-ls is started and misbehaving or if it is not even started?

I don't know how to check if it started. I can't see any difference after `mypy-ls` has been set to enabled. I want to help but don't know where to look.

**Comment by jordaneremieff** [comment]
@StabbarN What does your `LSP.sublime-settings` file look like? I came across this ticket when I was having similar problems getting live mode to work.

I initially tried defining the settings in `LSP-pylsp.sublime-settings`, but it was only when I included the settings in `LSP.sublime-settings` that it started working:
```json
// Settings in here override those in "LSP/LSP.sublime-settings"
{
    "clients": {
        "pylsp": {
            "enabled": true,
            "selector": "source.python",
            "command": [
                "path/to/.venv/bin/pylsp",
            ],
            "settings": {
                "pylsp.plugins.mypy_ls.enabled": true,
                "pylsp.plugins.mypy-ls.live_mode": true
            }
        }
    }
}
```

I didn't really dig into the reasons why one would work but the other would not, just sharing in case this might help.

**Comment by rchl** [comment]
> My sublime-project file:

I'm not sure what that `python_interpreter` setting is supposed to affect. It doesn't have anything to do with LSP-pylsp at least.

If you want pylsp to use your virtual environment then follow https://github.com/sublimelsp/LSP-pylsp#virtual-environments

To enable mypyls a settings like:

```
// Settings in here override those in "LSP-pylsp/LSP-pylsp.sublime-settings"
{
    "settings": {
        "pylsp.plugins.mypy_ls.enabled": true,
        "pylsp.plugins.mypy-ls.live_mode": false,
    }
}
```

should work. `live_mode` shouldn't be relevant but I'm fairly sure that `live_mode` has issues with locating types from imported files in some cases.

With a code like:

```py

def test(a: str) -> None:
    pass


test(1)
```
do you not see an error like:
![Screenshot 2021-06-14 at 17 46 06](https://user-images.githubusercontent.com/153197/121921397-420e5e80-cd39-11eb-918f-fac270b92b53.png)

(remember to save the file if you have `live_mode` disabled.

**Comment by StabbarN** [comment]
Setup as 
```
// Settings in here override those in "LSP/LSP.sublime-settings"
{
    "clients": {
        "pylsp": {
            "enabled": true,
            "selector": "source.python",
            "command": [
                "path/to/.venv/bin/pylsp",
            ],
            "settings": {
                "pylsp.plugins.mypy_ls.enabled": true,
                "pylsp.plugins.mypy-ls.live_mode": true
            }
        }
    }
}
```
seems to work after a quick test.

I've a lot of other stuffs going right now. I'll hopefully do more testing and verification in a few days.
Thanks for your help so far!

**Comment by rchl** [comment]
The only reason I can think of why this would work better for you is because you are running pylsp from your virtual environment. When using the `LSP-pylsp` package, the pylsp runs from package storage directory somewhere in user home directory. That's why when using `LSP-pylsp` you are supposed to follow https://github.com/sublimelsp/LSP-pylsp#virtual-environments to configure your project to use the python venv.

**Comment by Richardk2n** [comment]
It looks like you found a way, that works for you, and mypy-ls did not cause this issue. Is that correct? (Meaning can I close this now?)

**Comment by StabbarN** [comment]
I haven't verified it yet but my problem is probably that I haven't installed Python LSP Server manually as described at https://yeray.dev/python/setting-up-sublime-text-4-for-python#manual-setup

I was planning to install it manually and then close this issue. 

Yes, this issue can be closed.

Thank you for all responses!

**Comment by rchl** [comment]
There was a recent [related change](https://github.com/sublimelsp/lsp_utils/pull/67) made that might have fixed the original issues.
